---
kind: pipeline
name: build-load-tester

steps:
  - name: build_docker
    image: plugins/ecr
    settings:
      repo: 601394826940.dkr.ecr.us-east-2.amazonaws.com/load-tester
      region: us-east-2
      tags:
        - latest
        - ${DRONE_COMMIT}


  # - name: deploy_staging
  #   image: ktruckenmiller/ansible
  #   environment:
  #     AWS_DEFAULT_REGION: us-west-2
  #   commands:
  #    - ansible-playbook -i ansible_connection=localhost deployment/deploy.yml -e GIT_COMMIT=${DRONE_COMMIT} -e environ=staging -vvv

trigger:
  branch: master
  event: push
