---
- hosts: localhost
  gather_facts: false
  vars:
    name: test-ecs-cluster
    clustername: default
    network_config:
      us-west-2:
        subnet: subnet-9b2938c2
        vpc_id: vpc-849531e0
      us-east-2:
        subnet: subnet-0c00ee77
  tasks:
    - name: cloudformation
      cloudformation:
        stack_name: "{{name}}-ecs"
        state: present
        region: "{{region}}"
        template: "templates/task.yml"
        template_parameters:
          ServiceName: "{{ name }}"
          Environment: "{{environ}}"
          Version: "{{version}}"
          ClusterName: "{{clustername}}"
          VpcId: "{{ network_config[region]['vpc_id'] }}"
      register: ecs_task

    - name: debug
      debug: var=ecs_task
    - name: Simple PUT operation
      aws_s3:
        bucket: kloudcover
        object: tools/application-profiling/test.yml
        src: test.yml
        mode: put

    - name: run task
      command: "aws ecs run-task \
                --cluster=default \
                --task-definition test-load \
                --network-configuration='{\"awsvpcConfiguration\": {\"subnets\":[\"{{network_config[region]['subnet']}}\"],\"securityGroups\":[\"{{ecs_task.stack_outputs.Sg}}\"],\"assignPublicIp\": \"ENABLED\"}}' \
                --launch-type=FARGATE \
                --started-by=kevinisthebest \
                --count=1 \
                --overrides='{\"containerOverrides\": [{\"name\": \"{{ name }}\", \"environment\": [{\"name\": \"S3_LOCATION\", \"value\": \"s3://kloudcover/tools/application-profiling/test.yml\"}]}]}' \
                --region \"{{region}}\""
      register: task_res
