---
- hosts: localhost
  gather_facts: false
  vars:
    name: test-ecs-cluster
    clustername: default
  tasks:
    - name: cloudformation
      cloudformation:
        stack_name: "{{name}}-ecs"
        state: present
        region: "{{region}}"
        template: "templates/task.yml"
        template_parameters:
          ServiceName: "{{ name }}"
          Environment: "{{environ}}"
          Version: "{{version}}"
          ClusterName: "{{clustername}}"
      register: ecs_task

    - debug: var=ecs_task
    - name: RUN a task on Fargate
      ecs_task:
        operation: run
        cluster: "{{clustername}}"
        task_definition: "test-load"
        started_by: kevinisthebest
        count: 1
        launch_type: FARGATE
        region: "{{region}}"
        network_configuration:
          subnets:
          - subnet-0c00ee77
          security_groups:
          - sg-eaff2583
      register: task_output
